#!/bin/sh

createEpsD43()
{
    gnuplot<<EOF

    stats "$1" using 1 name "C" noout

    binwidth = 200
    xlow = C_min
    xhigh = C_max
    scale = (binwidth/(xhigh-xlow))
    bin(x) = (1.0/scale)*floor(x*scale)

    set terminal postscript eps enhanced color font 'Helvetica,24' linewidth 2
    set output "histogram.eps"
    set xlabel "X"
    set ylabel "number"
    set grid
    set size 1,1
    set autoscale

    plot '$1' using (bin(\$1)):(1) smooth frequency with boxes

EOF
}

# test if gnuplot exists on the system
if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

# paths to data
RVs="randomNumbers"

echo "    processing d43 profile" > log.createGraphs 2>&1

createEpsD43 $RVs

echo Done

#------------------------------------------------------------------------------
